# Generated by Django 2.2.24 on 2022-07-23 08:29

from django.db import migrations
import phonenumbers


def fix_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        phonenumber = flat.owners_phonenumber
        parsed_phonenumber = phonenumbers.parse(phonenumber, 'RU')
        fixed_phonenumber = phonenumbers.format_number(parsed_phonenumber, phonenumbers.PhoneNumberFormat.E164)
        flat.owner_pure_phone = fixed_phonenumber
        flat.save(update_fields=['owner_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20220723_1146'),
    ]

    operations = [
        migrations.RunPython(fix_phonenumbers),
    ]
