# Generated by Django 2.2.24 on 2022-07-27 13:09

from django.db import migrations
import phonenumbers


def fix_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phonenumber = flat.owners_phonenumber
        parsed_phonenumber = phonenumbers.parse(phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_phonenumber):
            fixed_phonenumber = phonenumbers.format_number(parsed_phonenumber, phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = fixed_phonenumber
            flat.save(update_fields=['owner_pure_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220726_2147'),
    ]

    operations = [
        migrations.RunPython(fix_phonenumbers),
    ]
