# Generated by Django 2.2.24 on 2022-07-27 13:18

from django.db import migrations

def fix_phonenumbers(apps, schema_editor):
    flats = apps.get_model('property', 'Flat')
    owners = apps.get_model('property', 'Owner')

    for flat in flats.objects.all():
        owner, is_created = owners.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )
        owner.flats_have.add(flat)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20220727_1609'),
    ]

    operations = [
        migrations.RunPython(fix_phonenumbers),
    ]
