# Generated by Django 2.2.24 on 2022-08-11 18:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20220803_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats_have',
            field=models.ManyToManyField(related_name='owners', to='property.Flat', verbose_name='Имеющиеся квартиры'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
